#MTBkMjcwYmU0MmU0NDlm
# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: vol_5
    vol_size: 10
  - vol_name: vol_6
    vol_size: 10

# Security group
security_groups:
- name: demo_ssh
  description: "Demo security group for SsH access"
  protocol: tcp
  port_range_min: 22
  port_range_max: 22
  remote_ip_prefix: 0.0.0.0/0
- name: demo_http
  description: "demo security group for Http"
  protocol: tcp
  port_range_min: 80
  port_range_max: 80
  #remote_ip_prefix: 128.250.0.0/16 
  remote_ip_prefix: 0.0.0.0/0

#Instance 
instance_name: webserver
instance_image: 955a0556-1224-4499-a895-87d54d5cbf32
instance_key_name: webKeys
instance_flavor: uom.mse.2c9g
