# Team number:67
# city: Melbourne
# Mengfeifei Zhang 877122
# Mohnish Panduranga Devadiga 1041730 
# Hangqi Yu 953852 
# Yi Li 917940
# Yijian Zhang 806676








 - hosts: harvester1
   vars_files:
    - host_vars/harvester1.yaml
   gather_facts: false
   become: yes
   roles:
      - role: harvestor_config
      - role: harvestor1

 - hosts: webserver
   vars_files:
    - host_vars/webserver.yaml
   become: yes
   gather_facts: true
   roles:
    - role: web_config
